version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_huggy
    env_file:
      - ./.env  
    volumes:
      - ./src:/src  
    working_dir: /src  
    command: ["python", "main.py"]
